"""add owner id

Revision ID: 13e15102de58
Revises: 1b45a0cf3503
Create Date: 2026-05-29 03:09:56.029388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e15102de58'
down_revision: Union[str, Sequence[str], None] = '1b45a0cf3503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'owner_id')
    # ### end Alembic commands ###
